[build]
builder = "nixpacks"
nixpacksVersion = "1.38.0"

[build.nixpacks]
nixPkgs = ["nodejs_22", "npm-10_x"]

[deploy]
startCommand = "npx serve -s dist -l 8080"
healthcheckPath = "/"
healthcheckTimeout = 100
