[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/healthcheck/api"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "sh -c 'alembic upgrade head && uvicorn src.network.http.launch:server --host 0.0.0.0 --port $PORT'"
